name: Health check trigger for Bot Extractor

on:
  schedule:
    - cron: '*/5 12-22 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger health endpoint
        run: |
          curl -X GET https://discord-bot-extractor.onrender.com/health

