name: Resume discord bot extractor every 8 PM PHT

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run resume command
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{secrets.RENDER_API_KEY}}" \
            https://api.render.com/v1/services/srv-cvpvo7uuk2gs73e9n6t0/resume