name: Resume discord bot extractor every 8 PM PHT

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  resume-service:
    runs-on: ubuntu-latest
    steps:
      - name: Run resume command
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{secrets.RENDER_API_KEY}}" \
            https://api.render.com/v1/services/srv-cvpvo7uuk2gs73e9n6t0/resume
  trigger-api:
    runs-on: ubuntu-latest
    needs: resume-service
    steps:
      - name: Trigger project build / spin up server
        run: |
          curl -X GET https://discord-bot-extractor.onrender.com/health