name: Suspend discord bot extractor every 6 AM PHT

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run suspend command
        run: |
          curl -X POST \ 
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \ 
          https://api.render.com/v1/services/YOUR_SERVICE_ID/resume